Update deploy.yaml

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -19,16 +19,16 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
+      - name: Configure DNS
+        run: |
+          echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
 
       - name: Test Network Connectivity
         run: |
-          curl -I https://adfvvcgbj.azurecr.io
+          curl -I https://adfvvcgbj.azurecr.io || echo "Failed to connect to container registry"
 
-      - name: Configure DNS
-        run: |
-          sudo echo "nameserver 8.8.8.8" > /etc/resolv.conf
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
 
       - name: Build and push Docker image
         run: ./scripts/build-image.sh
